# Buổi 03: Phân tích dữ liệu với Python

In [12]:
# !rm -r pydata-book
# !git clone https://github.com/wesm/pydata-book.git
!ls pydata-book/
# !sudo rm -r pydata-book/.git

COPYING     ch02.ipynb	ch06.ipynb  ch10.ipynb	datasets
README.md   ch03.ipynb	ch07.ipynb  ch11.ipynb	examples
appa.ipynb  ch04.ipynb	ch08.ipynb  ch12.ipynb	requirements.txt
appb.ipynb  ch05.ipynb	ch09.ipynb  ch13.ipynb


In [28]:
# !git status
# !git add . -n
# !git add .
# !git commit -m "buoi03"
# !git push
# !git status
# !git push --force # ép phải commit (nếu xảy ra xung đột)
# !git reset HEAD~  # phục hồi lại trạng thái commit gần nhất

# !git add .
# !git commit -m "buoi03"
# !git push

In [32]:
# !ls
# !mv pydata-book/ ../
# !git add . -n
# !git add .
# !git commit -m "buoi03"
# !git push

In [36]:
v = list(range(1, 6))
print(v)
print(2 * v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [38]:
import numpy as np
v = np.arange(1, 6)
print(v)
print(2 * v)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [40]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [42]:
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90


In [46]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[ 4 10 18]


In [2]:
import numpy as np

# Tạo mảng toàn số 0
a = np.zeros((5, 5))
print("Mảng toàn số 0:\n", a)

# Tạo mảng toàn số 1
b = np.ones((1, 2))
print("Mảng toàn số 1:\n", b)

# Tạo mảng với giá trị cố định là 7
c = np.full((2, 2), 7)
print("Mảng toàn số 7:\n", c)

# Tạo ma trận đơn vị 2x2
d = np.eye(2)
print("Ma trận đơn vị:\n", d)

# Tạo mảng với giá trị ngẫu nhiên từ 0 đến 1
e = np.random.random((2, 2))
print("Mảng ngẫu nhiên:\n", e)


Mảng toàn số 0:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Mảng toàn số 1:
 [[1. 1.]]
Mảng toàn số 7:
 [[7 7]
 [7 7]]
Ma trận đơn vị:
 [[1. 0.]
 [0. 1.]]
Mảng ngẫu nhiên:
 [[0.58733915 0.73928744]
 [0.74592243 0.26530296]]


In [11]:
import numpy as np
a = np.arange(15)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

a = a.reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)
1
int64
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64


In [14]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [17]:
b = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
b = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23],
])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
(3, 4)
int64


In [26]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[:2,1:], a[:2,1:].shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]] (2, 2)


## Kết thúc